#
# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: magnum-common | _set_directories | set service etc and venv directory
  set_fact:
    magnum_service_conf_dir: >
      {{ magnum_component | config_dir(install_package_result.version) }}/magnum
    magnum_service_bin_dir: >
      {{ magnum_component | bin_dir(install_package_result.version) }}
  when: install_package_result.version is defined

- name: magnum-common | _set_directories | set service etc and venv directory
  set_fact:
    magnum_service_conf_dir: "{{ magnum_component | config_dir() }}/magnum"
    magnum_service_bin_dir: "{{ magnum_component | bin_dir() }}"
  when: install_package_result.version is undefined
